### ISSUE TITLE
感觉后面可以增加一些其他的弹幕来源

### ISSUE THREAD

**Issue by Geeksun2018** [Izumiko/jellyfin-danmaku#11]
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/42086593/ed9ef71f-324b-4a3c-b236-f3f7674b5227)
可以参考这个repository，增加一些爱奇艺、优酷、腾讯视频的弹幕。这样看很多电影资源应该也可以有弹幕了。有空我研究一下，看看能不能接入进来。

**Comment by Xarth-Mai** [comment]
B站的弹幕质量已经不咋样了,再加入爱奇艺、优酷、腾讯视频就是一坨屎了

**Comment by Geeksun2018** [comment]
> B站的弹幕质量已经不咋样了,再加入爱奇艺、优酷、腾讯视频就是一坨屎了

确实是，之前在腾讯视频看电影的时候，某些弹幕资源质量确实不行。不知道还有哪些网站弹幕质量比较高，且弹弹play还没收录的。感觉番剧类的弹幕资源现在应该比较全了，可能其他类别会欠缺一些。

**Comment by Xarth-Mai** [comment]
### 不用想了,简中基本都是低质量

**Comment by Geeksun2018** [comment]
> ### 不用想了,简中基本都是低质量 特别是在非国产片 粉红太多太恶心

哈哈哈，这样子，那暂时先这样！

**Comment by Xarth-Mai** [comment]
经过测试 dandanplay其实是会整合iqiyi的弹幕的
