### ISSUE TITLE
这个已经可以用了吗？安装脚本后什么都没发生

### ISSUE THREAD

**Issue by aoout** [Izumiko/jellyfin-danmaku#2]

**Comment by Geeksun2018** [comment]
> _No description provided._

需要清除一下cookie和缓存，我清除了倒是可以显示了，但是好像还有点问题。

**Comment by aoout** [comment]
> > _No description provided._
> 
> 需要清除一下cookie和缓存，我清除了倒是可以显示了，但是好像还有点问题。

什么问题？

**Comment by Geeksun2018** [comment]
> > > _No description provided._
> > 
> > 
> > 需要清除一下cookie和缓存，我清除了倒是可以显示了，但是好像还有点问题。
> 
> 什么问题？

弹幕还是没加载出来，感觉可能是没搜索到弹幕的原因，待会有空研究一下。

**Comment by aoout** [comment]
it works. thanks to developer.
