### ISSUE TITLE
[BUG]Firefox CORS Error

### ISSUE THREAD

**Issue by DEAN-Cherry** [Izumiko/jellyfin-danmaku#21]
**Version**

- jellyfin version latest
- jellyfin-danmaku version latest

**Describe the bug**
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/76607677/eb03882f-1c82-4ef6-b87b-8372ae55f337)
Firfox 中使用 `jellyfin-danmaku` 会报 CORS 错误

**To Reproduce**
 使用任意方法开启均会引起，在 edge/chrome 中均无问题已经尝试过 油猴/ NGINX 方法。在Firefox中单独访问 api 接口能够返回正常。

**Comment by Izumiko** [comment]
在 62f6f53 里面处理了一下跨域的OPTIONS请求，你再试试

**Comment by DEAN-Cherry** [comment]
![图片](https://github.com/Izumiko/jellyfin-danmaku/assets/76607677/5298a5d5-f580-4bfe-a7b8-12cc3c195e50)
Works Great now
THX!
