### ISSUE TITLE
[UR/FR]对Jellyfin Windows PC客户端的支持

### ISSUE THREAD

**Issue by Youwenqwq** [Izumiko/jellyfin-danmaku#23]
希望能够支持PC端的Jellyfin客户端。

PC端的Jellyfin客户端主界面采用本地文件中的资源，index.html等文件存储在程序安装目录`Jellyfin\Jellyfin Media Player\web-client\desktop`中，可以直接在本地使用文本编辑器进行修改，从而加入脚本。

不过，直接加入本项目脚本会因为本地的资源路径和浏览器上访问的不一致(例如`web/index.html`在本地是`web-client/desktop/index.html`)，这导致该脚本无法正常在播放界面显示。

本人不会JavaScript（入门都没入ヽ(*。>Д<)o゜）不知道怎么修改，因此希望在这个issue里给作者一个可行的思路，看看是否能成（（

在桌面客户端[项目仓库](https://github.com/jellyfin/jellyfin-media-player)的README.md中有Web Debugger的连接方法，可以看看

**Comment by Izumiko** [comment]
初步看了一下，应该是不行。弹幕插件依赖网页里的<video>标签作为媒体来源，但是PC客户端并不是通过<video>来播放的视频，估计是用原生的方式实现的播放。这样弹幕就没法和视频同步播放了

**Comment by Youwenqwq** [comment]
> 初步看了一下，应该是不行。弹幕插件依赖网页里的`<video>`标签作为媒体来源，但是PC客户端并不是通过`<video>`来播放的视频，估计是用原生的方式实现的播放。这样弹幕就没法和视频同步播放了

理解，感谢提供支持
