### ISSUE TITLE
[BUG] 搜索弹幕时出现 SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by I-love-study** [Izumiko/jellyfin-danmaku#25]
**Version**

- jellyfin version: 10.8.13
- jellyfin-danmaku version: 1.20

**Describe the bug**

在尝试手动搜索弹幕时，会出现以下相关日志

```text
手动匹配弹幕
准备获取Item信息
等待Config
获取服务器信息
尝试获取DevId
SyntaxError: Unexpected end of JSON
```

在初始化界面会有如下信息

```text
准备获取Item信息
正在获取Item信息
成功 憧憬成为魔法少女
弹幕查询无结果
播放器未完成加载
```

**To Reproduce**

1. 进入一个在弹弹play上并没有弹幕的节目
   比如上图因为翻译问题导致无法识别的“憧憬成为魔法少女”（弹弹play上是“梦想成为魔法少女”）
2. 点击“搜索弹幕”

**Expected behavior**

按下“搜索弹幕”按钮后，能够选择弹幕

**Screenshots**

<img width="1227" alt="image" src="https://github.com/Izumiko/jellyfin-danmaku/assets/39652142/7f40627e-3d0e-4539-9a13-6a936a64c53d">

**Additional context**

将番名改成“梦想成为魔法少女”后，点击“搜索弹幕”可以按照预期出现弹窗

**Comment by Xarth-Mai** [comment]
看起来像是获取DevId失败，所以刷新页面后就可以运行了。看起来和番名没啥关系

**Comment by I-love-study** [comment]
看起来是这样的
十分感谢
