### ISSUE TITLE
[FR] 有可能增加发送弹幕的功能吗

### ISSUE THREAD

**Issue by littleplus** [Izumiko/jellyfin-danmaku#33]
插件很好用，目前用的是nginx配置替换body方式安装的，不知道是否方便增加一个发送弹幕的功能，只是看着弹幕感觉缺少了一点参与感（笑

**Comment by Xarth-Mai** [comment]
#22

**Comment by Xarth-Mai** [comment]
能做 但是，没人做

**Comment by Izumiko** [comment]
简单写了一个，但暂时还无法测试，缺少相关的appId和appSecret，我向弹弹Play的开发者申请了，等等他的回复

**Comment by littleplus** [comment]
@Izumiko 感谢大佬~那我就等大佬的消息了

**Comment by Izumiko** [comment]
暂时借用了另一个项目的appId，你可以更新脚本测试一下了

**Comment by littleplus** [comment]
怪了，我什么配置也没变，但是nginx替换突然失效了，重启nginx也没用，最后是将 body更改成head才好（估计是修改了一下重新生成了配置）

**Comment by littleplus** [comment]
看起来登录和发送弹幕的功能都没有报错，回看也能正常显示发出的弹幕

**Comment by Izumiko** [comment]
> 怪了，我什么配置也没变，但是nginx替换突然失效了，重启nginx也没用，最后是将 body更改成head才好（估计是修改了一下重新生成了配置）

Jellyfin网页在打开之后，会在浏览器注册Service Worker，之后你再访问Jellyfin时，会从Service Worker直接加载网页，而不是通过服务器，所以你失效有可能是因为你打开的是它缓存的旧版网页。可以按F12进控制台，然后到对应设置那里取消注册一下

**Comment by Izumiko** [comment]
appid暂时申请不到了，先这样用吧
