### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Xarth-Mai** [Izumiko/jellyfin-danmaku#36]

**Comment by Xarth-Mai** [comment]
无痕模式下不止手动搜番 第一次播放的自动搜番也坏掉了

**Comment by Xarth-Mai** [comment]
最新的这个版本是这样的

**Comment by Izumiko** [comment]
你再看看，发现之前手滑打错单词了

**Comment by Xarth-Mai** [comment]
好了

**Comment by Izumiko** [comment]
改这段的时候是为了改善一下OVA相关的搜索和显示，正常的TVSeries忘记测了

**Comment by Xarth-Mai** [comment]
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/72293030/f47be007-aa78-45de-b016-7390c3cd6dc2)
这个字的颜色，看不清捏 
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/72293030/94549a85-3557-45bf-a408-eb5e788d86d8)
在这找到一个Jellyfin主题的变量（图片右边），但是我不懂怎么用上去，这个变量是Jy自带的菜单在用的

**Comment by Xarth-Mai** [comment]
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/72293030/e5359922-3dab-4ca3-ae8b-d22245e61ec8)![image](https://github.com/Izumiko/jellyfin-danmaku/assets/72293030/b36622c2-cd1e-4b29-ba6d-58302ed1978f)
这个发送界面一部分到屏幕下方去了，比较极端的情况如图一摸不到按钮了
而且字体好像没有正确复制dialog的颜色，有点淡

**Comment by Xarth-Mai** [comment]
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/72293030/7d391185-1b28-48bd-ba03-d4d917904f7b)
Safari这个BUG居然还在Σ(¯□¯||) 触发这个错误后脚本就直接死了，需要重开

**Comment by Izumiko** [comment]
我先把发送界面那个回滚了吧，没设计好

**Comment by Xarth-Mai** [comment]
> 我先把发送界面那个回滚了吧，没设计好

你开学了吗😱

**Comment by Izumiko** [comment]
开了呀

**Comment by Xarth-Mai** [comment]
大事不好了老師.現在看一半返回主頁換別的影片的話,彈幕會加載不出來
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/72293030/59ff18a4-a8e3-47a2-ad82-498a01bf4672)

**Comment by Izumiko** [comment]
那估计是我这个 b6f058a 没修完全。看样子不应该直接destory弹幕对象，我把wrapper隐藏了一下，然后让后续的函数重新创建弹幕对象吧。 4c839a3 这个看着貌似可以了

**Comment by Xarth-Mai** [comment]
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/72293030/94c1cf73-9c31-4dea-927b-908bd02b9899)
这个dandanplay的弹幕和B站野生视频的弹幕居然也有重复 现在这个版本看轻音少女经常遇到这种三条重复的弹幕/(ㄒoㄒ)/~~
比较粗暴的方法好像是屏蔽www.bilibili.com/video/av11111这种野生资源,只保留www.bilibili.com/bangumi/play/ep1111111

**Comment by Izumiko** [comment]
> ![image](https://private-user-images.githubusercontent.com/72293030/345303017-94c1cf73-9c31-4dea-927b-908bd02b9899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjQyNjQsIm5iZiI6MTcyMDE2Mzk2NCwicGF0aCI6Ii83MjI5MzAzMC8zNDUzMDMwMTctOTRjMWNmNzMtOWMzMS00ZGVhLTkyN2ItOTA4YmQwMmI5ODk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5Nzc3NDMxZDVjMGU3OTFiMjgzOWUxN2JhZWU3ZmE5YTg1ZTkwNTg1ZjBiNDI1NzFkNzBiNWE3YzM0NWUyMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.itgjBJf_dxjNH-lE3DtB-BxEOjXzlYlcPESSTPj-qWg)
> 
> 这个DanDanPlay的弹幕和B站野生视频的弹幕居然也有重复 现在这个版本看轻音少女经常遇到这种三条重复的弹幕/(ㄒoㄒ)/~~
> 
> 也测了下JOJO的第一季,也有这样额外的两个野生资源,但是没有重复的弹幕
> 
> 这是看轻音时获取到的源,重复的都来自后两个野生资源:
> 
> ```json
> [
>     {
>         "url": "https://www.bilibili.com/bangumi/play/ep21286",
>         "shift": 0
>     },
>     {
>         "url": "http://www.bilibili.com/video/av1700631/index_8.html",
>         "shift": 0
>     },
>     {
>         "url": "http://www.bilibili.com/video/av29176/index_8.html",
>         "shift": 0
>     }
> ]
> ```
> 
> 捣鼓了半天好像只有给这种野生资源单独加个开关能比较简单解决

没想到不同来源不仅cid不一样，连用户名都不一样。修改了一下重复弹幕的判定，去掉了用户名 d9bba73162d39f85a191fcfc808b0239f5e03bea ，现在只用`时间,模式,颜色,内容`作为key

**Comment by Xarth-Mai** [comment]
> 
> 没想到不同来源不仅cid不一样，连用户名都不一样。修改了一下重复弹幕的判定，去掉了用户名 d9bba73162d39f85a191fcfc808b0239f5e03bea ，现在只用`时间,模式,颜色,内容`

源数据确实很复杂，如我上面发的图，有个源的时间和另两个源差了一秒 甚至一条来自B站一条来自弹弹😨

**Comment by Xarth-Mai** [comment]
弹幕来源过滤出现了BUG
好像是这个提交https://github.com/Izumiko/jellyfin-danmaku/commit/0e5a3b008783c9cecfacd75a002d3d062fc8c29a
```
const user = comment.p.split(',')[3];
const modeId = parseInt(comment.p.split(',')[1], 10);
return !danmakuFilteRule.test(comment.m) && enabledMode.includes(modeId);
```
最后一行应该是
```
return !danmakuFilteRule.test(user) && enabledMode.includes(modeId);
```
原先这里定义了一个user却没有引用🤔
