### ISSUE TITLE
[UR/FR]jellyfin安卓端适配

### ISSUE THREAD

**Issue by Geeksun2018** [Izumiko/jellyfin-danmaku#4]
请问这个后续会支持安卓端的jellyfin嘛？

**Comment by Izumiko** [comment]
安卓端的没测试过，目前在iPad用的客户端是直接调用服务端的文件，所以我在服务端改完之后就直接生效了。如果安卓端是把资源文件打包进apk的话，那估计就得修改apk了，这个我不太会

**Comment by Geeksun2018** [comment]
> 安卓端的没测试过，目前在iPad用的客户端是直接调用服务端的文件，所以我在服务端改完之后就直接生效了。如果安卓端是把资源文件打包进apk的话，那估计就得修改apk了，这个我不太会

好的，我去参考一下embly那边的做法，看看是否可以让手机端也支持弹幕功能。我昨天想试试看能否在手机浏览器上装tampermonkey，但是手机浏览器支持好像不太好。
