### ISSUE TITLE
[BUG]在iPad上运行脚本时会不停重设容器大小导致弹幕会反复加载，或者流动到一半就消失了

### ISSUE THREAD

**Issue by index20481** [Izumiko/jellyfin-danmaku#40]
**描述**
浏览器用的是Gear,直接导入的脚本。
试过用safari+userscripe，但一直没效果。

**Screenshots**
![IMG_0414](https://github.com/Izumiko/jellyfin-danmaku/assets/77374137/f3315e13-d081-4d28-aa95-508fad39b2e7)

**Comment by Xarth-Mai** [comment]
但是重设容器大小不会重新加载弹幕,是那个'侦测到播放媒体变化'在反复触发

**Comment by Xarth-Mai** [comment]
没有订阅Gear浏览器测试不了相同环境 但是尝试修复了这个死循环
https://github.com/Xarth-Mai/jellyfin-danmaku/raw/jellyfin/ede.js
因为仓库分支问题,混进去一些我的别的修改 可能跟现在用的1.33版本有差异 在我的Safari上是正常的

**Comment by index20481** [comment]
重新导入后试了一下发现还是有这个问题，在探测播放媒体变化X4后还是陷入了和之前一样的循环。。。。。。
![1](https://github.com/Izumiko/jellyfin-danmaku/assets/77374137/70b638f6-b082-49d9-8502-6931c1ffdcbc)

我还是试试在safari上好了。但是在safari上还是没将插件加载成功，你也是用的userscripts吗？

**Comment by index20481** [comment]
> 没有订阅Gear浏览器测试不了相同环境 但是尝试修复了这个死循环 https://github.com/Xarth-Mai/jellyfin-danmaku/raw/jellyfin/ede.js 因为仓库分支问题,混进去一些我的别的修改 可能跟现在用的1.33版本有差异 在我的Safari上是正常的

重新导入后试了一下发现还是有这个问题，在探测播放媒体变化X4后还是陷入了和之前一样的循环。。。。。。
![1](https://github.com/Izumiko/jellyfin-danmaku/assets/77374137/8f07efe8-9e9e-40c4-80b2-d89b40a09ceb)


我还是试试在safari上好了。但是在safari上还是没将插件加载成功，你也是用的userscripts吗？

**Comment by Izumiko** [comment]
> 没有订阅Gear浏览器测试不了相同环境 但是尝试修复了这个死循环 https://github.com/Xarth-Mai/jellyfin-danmaku/raw/jellyfin/ede.js 因为仓库分支问题,混进去一些我的别的修改 可能跟现在用的1.33版本有差异 在我的Safari上是正常的

探测播放媒体变化那个是video标签属性有改动的时候会触发，你只改成refresh可能区别不大。正常video标签是在切换播放的视频时才会变，对应的回调函数只会调用一次。不知道是不是Gear浏览器对video标签做过改动，导致触发了多次

**Comment by index20481** [comment]
> > 没有订阅Gear浏览器测试不了相同环境 但是尝试修复了这个死循环 https://github.com/Xarth-Mai/jellyfin-danmaku/raw/jellyfin/ede.js 因为仓库分支问题,混进去一些我的别的修改 可能跟现在用的1.33版本有差异 在我的Safari上是正常的
> 
> 探测播放媒体变化那个是video标签属性有改动的时候会触发，你只改成refresh可能区别不大。正常video标签是在切换播放的视频时才会变，对应的回调函数只会调用一次。不知道是不是Gear浏览器对video标签做过改动，导致触发了多次

确实，我也感觉是浏览器的问题，打算换回safari了。😶
但我的safari一直不能正常加载这个脚本不知道啥原因，用的userscripts。😑

**Comment by Izumiko** [comment]
> 确实，我也感觉是浏览器的问题，打算换回safari了。😶 但我的safari一直不能正常加载这个脚本不知道啥原因，用的userscripts。😑

我用修改服务端那几种方法，油猴脚本只用在桌面浏览器。修改服务端的话，Jellyfin的iOS客户端都可以直接兼容

**Comment by index20481** [comment]
> > 确实，我也感觉是浏览器的问题，打算换回safari了。😶 但我的safari一直不能正常加载这个脚本不知道啥原因，用的userscripts。😑
> 
> 我用修改服务端那几种方法，油猴脚本只用在桌面浏览器。修改服务端的话，Jellyfin的iOS客户端都可以直接兼容

行那我也试一下，谢谢♪(´▽｀)

**Comment by Xarth-Mai** [comment]
> > 没有订阅Gear浏览器测试不了相同环境 但是尝试修复了这个死循环 https://github.com/Xarth-Mai/jellyfin-danmaku/raw/jellyfin/ede.js 因为仓库分支问题,混进去一些我的别的修改 可能跟现在用的1.33版本有差异 在我的Safari上是正常的
> 
> 
> 
> 探测播放媒体变化那个是video标签属性有改动的时候会触发，你只改成refresh可能区别不大。正常video标签是在切换播放的视频时才会变，对应的回调函数只会调用一次。不知道是不是Gear浏览器对video标签做过改动，导致触发了多次

我的想法是改成refresh在后续判断剧集没变的话应该就结束函数了 但是好像没什么效果

**Comment by Xarth-Mai** [comment]
> > > 没有订阅Gear浏览器测试不了相同环境 但是尝试修复了这个死循环 https://github.com/Xarth-Mai/jellyfin-danmaku/raw/jellyfin/ede.js 因为仓库分支问题,混进去一些我的别的修改 可能跟现在用的1.33版本有差异 在我的Safari上是正常的
> 
> > 
> 
> > 探测播放媒体变化那个是video标签属性有改动的时候会触发，你只改成refresh可能区别不大。正常video标签是在切换播放的视频时才会变，对应的回调函数只会调用一次。不知道是不是Gear浏览器对video标签做过改动，导致触发了多次
> 
> 
> 
> 确实，我也感觉是浏览器的问题，打算换回safari了。😶
> 
> 但我的safari一直不能正常加载这个脚本不知道啥原因，用的userscripts。😑

我用stay也不能正常加载，我记得十几个版本之前就是可以🤔

**Comment by index20481** [comment]
> > > > 没有订阅Gear浏览器测试不了相同环境 但是尝试修复了这个死循环 https://github.com/Xarth-Mai/jellyfin-danmaku/raw/jellyfin/ede.js 因为仓库分支问题,混进去一些我的别的修改 可能跟现在用的1.33版本有差异 在我的Safari上是正常的
> > 
> > > 
> > 
> > > 探测播放媒体变化那个是video标签属性有改动的时候会触发，你只改成refresh可能区别不大。正常video标签是在切换播放的视频时才会变，对应的回调函数只会调用一次。不知道是不是Gear浏览器对video标签做过改动，导致触发了多次
> > 
> > 
> > 
> > 确实，我也感觉是浏览器的问题，打算换回safari了。😶
> > 
> > 但我的safari一直不能正常加载这个脚本不知道啥原因，用的userscripts。😑
> 
> 我用stay也不能正常加载，我记得十几个版本之前就是可以🤔

就很神奇，不过已经改成反向代理正常使用了，感谢😯
