### ISSUE TITLE
请问可以在Windows服务器端安装吗[UR/FR]

### ISSUE THREAD

**Issue by w-calvin** [Izumiko/jellyfin-danmaku#42]
**Is your feature request related to a problem? Please describe.**

因为历史原因（x），服务器端使用的是官网的jellyfin for windows server，在Readme中没有看到Windows服务器端配置的方法。如果使用扩展方案，需要在各客户端安装扩展（此外例如Android端使用官网jellyfin for Android，不方便安装扩展）。希望可以在Windows服务器端一次性安装。

**Describe the solution you'd like**

请问如何在jellyfin for Windows server端安装，或是否会支持该功能？

**Comment by Izumiko** [comment]
应该是没问题的，找到Windows版的index.html，然后按照方法4添加内容

**Comment by w-calvin** [comment]
可以了，谢谢

> 应该是没问题的，找到Windows版的index.html，然后按照方法4添加内容
