### ISSUE TITLE
[BUG]手动修改客户端标签后弹幕显示位置不在画面顶端

### ISSUE THREAD

**Issue by APecme** [Izumiko/jellyfin-danmaku#43]
![2024-04-27_08-01-56](https://github.com/Izumiko/jellyfin-danmaku/assets/152749864/a634c03d-a678-4467-8241-b17ed36929f2)

弹幕顶端位置不在画面顶端

**Comment by APecme** [comment]
发现了原因是我使用了jellyfin的第三方插件皮肤，请问有办法解决吗

**Comment by Izumiko** [comment]
@Xarth-Mai 我最近在赶deadline，没啥时间，你有空帮忙看一下么？

**Comment by Xarth-Mai** [comment]
> @Xarth-Mai 我最近在赶deadline，没啥时间，你有空帮忙看一下么？

Okey.I will try

**Comment by Xarth-Mai** [comment]
> 发现了原因是我使用了jellyfin的第三方插件皮肤，请问有办法解决吗

https://github.com/ranzonsan/JellySkin-SC  我试了一下这个主题 有这个问题

**Comment by Xarth-Mai** [comment]
@APecme 
### 临时解决方法 修改Jellyfin控制台中的自定义CSS
> 这是原本的皮肤设置
```
@import url("https://cdn.jsdelivr.net/npm/jellyskin-sc@latest/dist/main.css");
@import url("https://cdn.jsdelivr.net/npm/jellyskin-sc@latest/dist/logo.css");
```
> 这是修改的三个样式 覆盖原有样式
```
.mainAnimatedPages.skinBody {
    position: unset !important;
}
.dashboardDocument .skinBody {
    position: relative !important;
}
.pageTabContent {
    position: relative !important;
    top: 100px !important;
}
```
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/72293030/f533e92c-c4c0-45ce-8185-a7b18e774094)

**Comment by Xarth-Mai** [comment]
嘻嘻

**Comment by APecme** [comment]
我直接添加了覆盖原有风格的CSS，没有发现添加的按钮变乱的情况，问题完美解决了。感谢你
![2024-04-30_02-32-51](https://github.com/Izumiko/jellyfin-danmaku/assets/152749864/26cbf2fc-0488-4151-8093-8a77d5fed53f)

**Comment by Xarth-Mai** [comment]
> 
> ![2024-04-30_02-32-51](https://github.com/Izumiko/jellyfin-danmaku/assets/152749864/26cbf2fc-0488-4151-8093-8a77d5fed53f)
> 

底下这几个图标的显示不正常🤓

**Comment by APecme** [comment]
我以为他这样就是正常的，用这个皮肤修复之前他也是这样🤔

**Comment by Xarth-Mai** [comment]
> 我以为他这样就是正常的，用这个皮肤修复之前他也是这样🤔

没改图标部分 因为改了这部分正常后 其他按钮又会乱掉，要去脚本里针对这个主题设定一遍图标
