### ISSUE TITLE
[UR/FR] 希望可以添加选项调整从其它网站获取弹幕的最小弹幕数量阈值/主动获取其他网站弹幕

### ISSUE THREAD

**Issue by Youwenqwq** [Izumiko/jellyfin-danmaku#45]
如题，希望可以添加选项调整从其它网站获取弹幕的最小弹幕数量阈值/主动获取其他网站弹幕。

想法来源是，一起使用jellyfin的同学喜欢b站用户风格的字幕，但弹弹play在默认情况下会有从其它网站上获取弹幕的阈值。在Windows客户端中，弹弹play的默认弹幕阈值为800，即若弹弹play服务器上的弹幕数量大于800就不从第三方网站（如B站）上额外获取弹幕。这会导致可能弹幕数量刚刚好超过800一点点就不加载其他网站，造成弹幕数量依旧不够多的情况。

在弹弹play的windows客户端中存在如下设置选项可以调节，因此希望可以增加该功能，或者手动选择需要额外加载的网站弹幕（非现有功能中的弹幕过滤）。
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/25259258/54895eee-b7c0-4e72-8af3-0a72cf62359b)

**Comment by Izumiko** [comment]
现有的版本就是获取包括第三方弹幕的所有弹幕。即API中的`withRelated`参数，[文档](https://api.dandanplay.net/swagger/ui/index#!/Comment/Comment_GetAsync)。

https://github.com/Izumiko/jellyfin-danmaku/blob/7fba6dd2d8f3dbd536291de715c00802b2ab00b3/ede.js#L914

**Comment by Youwenqwq** [comment]
> 现有的版本就是获取包括第三方弹幕的所有弹幕。即API中的`withRelated`参数，[文档](https://api.dandanplay.net/swagger/ui/index#!/Comment/Comment_GetAsync)。
> 
> https://github.com/Izumiko/jellyfin-danmaku/blob/7fba6dd2d8f3dbd536291de715c00802b2ab00b3/ede.js#L914

感谢提供帮助，不过根据我的测试，目前版本确实是只加载了弹弹play自己的弹幕集
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/25259258/7f936ae6-2ae4-42e4-ad4f-90c2c2794f3b)
2767个，与客户端读取到的弹弹play自身服务器提供的弹幕数量一致，并且观看过程中并未发现有b站字幕。经测试，在弹弹play客户端中拉高阈值可以正常地自动获取弹幕

**Comment by Izumiko** [comment]
测试了一下是这样，`withRelated`参数在你这个情况下未生效。查询`/api/v2/related/{episodeId}`接口能获取到b站等的播放地址，然后用这些地址再调用`/api/v2/extcomment`能拿到额外的弹幕。但是这样一来就要请求好多次来判断了

**Comment by Youwenqwq** [comment]
请问为啥我目前这个情况无法使withRelated生效呢qwq

**Comment by Izumiko** [comment]
按照现在公开的API貌似没法一步完成，或许和你前边提到的客户端里面那个设置功能有关，但是文档里面没提怎么用。

目前我能想到的是这样弄：请求一次`withRelated=false`，一次`withRelated=true`，若两次获取的弹幕数量相同，且获取`/api/v2/related`不为空，就再依次根据第三方弹幕源用`/api/v2/extcomment`获取弹幕，最后再把几个源的合并，然后显示。

看着有些折腾，要是没有更好的方法的话，就考虑用这种。

**Comment by Xarth-Mai** [comment]
> 看着有些折腾，要是没有更好的方法的话，就考虑用这种。

- 可以在本地可以判断到有没有来自baha或者bili的弹幕吧，然后再根据过滤器设置去补全一下弹幕源

**Comment by Xarth-Mai** [comment]
> 在本地可以判断到有没有来自baha或者bili的弹幕吧 然后再根据过滤器设置去补全一下弹幕源 可以减少一次对弹弹API的请求

不对，既然这样为什么不直接根据过滤设置单独请求 弹弹 哔哩 巴哈

就不用再做本地的过滤了 但是对比现版本每次播放至多要多请求三次API

**Comment by Izumiko** [comment]
已实现 d76a770
![图片](https://github.com/Izumiko/jellyfin-danmaku/assets/5195868/04a12135-39ab-4229-b112-e1a069dc914b)

**Comment by Youwenqwq** [comment]
ok，感谢开发者~
