### ISSUE TITLE
[UR/FR] 较小的高度比例，弹幕多的时候，容易挤成一坨，能否改进一下显示弹幕的算法？

### ISSUE THREAD

**Issue by mrzhu666** [Izumiko/jellyfin-danmaku#47]
把弹幕密度限制等级拉到最高也没用。能否把显示弹幕严格按照行划分，控制出现速度

![image](https://github.com/Izumiko/jellyfin-danmaku/assets/47910447/a50da7a1-c3d9-4d4a-a208-59aa73e76ea7)

**Comment by mrzhu666** [comment]
设置参数
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/47910447/310371d1-80ab-4133-b1e9-f296acb1ea59)

显示效果
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/47910447/06740a47-4f56-4f93-932c-44cb366deff0)

**Comment by Izumiko** [comment]
根据弹幕持续时间修改了一下限制，你试试效果

**Comment by mrzhu666** [comment]
1920x1280分辨率的surface
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/47910447/924aa75e-9724-46ca-8614-942f5500fd68)

![image](https://github.com/Izumiko/jellyfin-danmaku/assets/47910447/0da6a196-9184-4a4d-94ce-803e97e7b874)

好像非16:9分辨率容易出现上下行重叠的情况，而且弹幕速度不一致还是叠起来

不知道你有没有用过弹弹play，它采取的方法是，不管弹幕文字数所有弹幕统一速度，按照行数参数显示弹幕，顶部弹幕全部转滚动。如果可以往这个这方向优化感谢

**Comment by Xarth-Mai** [comment]
> 根据弹幕持续时间修改了一下限制，你试试效果

从日志里看，密度限制功能好像罢工了喔

**Comment by Xarth-Mai** [comment]
> 
> 好像非16:9分辨率容易出现上下行重叠的情况，而且弹幕速度不一致还是叠起来
>

新版本的过滤应该不会再有重叠了
