### ISSUE TITLE
[BUG]Cannot read properties of null

### ISSUE THREAD

**Issue by Hammer2333** [Izumiko/jellyfin-danmaku#49]
昨天出现的情况，我目前使用的方式是直接修改服务器的index.html，前一段时间使用很正常，浏览器插件我也测试了一下也是有同样的问题
![屏幕截图 2024-06-06 103335](https://github.com/Izumiko/jellyfin-danmaku/assets/80084984/4c20dba4-c2c4-40b1-96c2-0aa9b58edbd3)

**Comment by Izumiko** [comment]
@Xarth-Mai 是不是你昨天加的那个并行添加第三方弹幕的问题？

**Comment by Xarth-Mai** [comment]
> @Xarth-Mai 是不是你昨天加的那个并行添加第三方弹幕的问题？

布吉岛啊 这个日志看不出东西来

**Comment by Hammer2333** [comment]
> > @Xarth-Mai 是不是你昨天加的那个并行添加第三方弹幕的问题？
> 
> 布吉岛啊 这个日志看不出东西来 那个地方如果有出问题应该是网络出问题了吧

![屏幕截图 2024-06-06 211650](https://github.com/Izumiko/jellyfin-danmaku/assets/80084984/4ec777c7-9392-4448-96a4-36634e876e90)
![屏幕截图 2024-06-06 211410](https://github.com/Izumiko/jellyfin-danmaku/assets/80084984/f382f49d-de4d-4671-af76-0bfd09931d9b)
感觉不太像网络问题，我开不开代理都是一个错误，实在找不到问题出在哪了

**Comment by Izumiko** [comment]
@Hammer2333 你用油猴脚本模式试试把[这个commit](https://github.com/Izumiko/jellyfin-danmaku/commit/bdb240975b4d488c2871d0d72880ec56133e2879)的更改还原之后能否正常

不行的话再还原一下[第二个commit](https://github.com/Izumiko/jellyfin-danmaku/commit/d79a8ac792f5008f7225fa45f96b208c16145d2d)

**Comment by Hammer2333** [comment]
> @Hammer2333 你用油猴脚本模式试试把[这个commit](https://github.com/Izumiko/jellyfin-danmaku/commit/bdb240975b4d488c2871d0d72880ec56133e2879)的更改还原之后能否正常

还原后也没什么作用，这一段我看也没动video元素，感觉主要问题还是脚本获取不到video

**Comment by Izumiko** [comment]
> > @Hammer2333 你用油猴脚本模式试试把[这个commit](https://github.com/Izumiko/jellyfin-danmaku/commit/bdb240975b4d488c2871d0d72880ec56133e2879)的更改还原之后能否正常
> 
> 还原后也没什么作用，这一段我看也没动video元素，感觉主要问题还是脚本获取不到video

那估计就是第二个commit导致的了

**Comment by Hammer2333** [comment]
> > > @Hammer2333 你用油猴脚本模式试试把[这个commit](https://github.com/Izumiko/jellyfin-danmaku/commit/bdb240975b4d488c2871d0d72880ec56133e2879)的更改还原之后能否正常
> > 
> > 
> > 还原后也没什么作用，这一段我看也没动video元素，感觉主要问题还是脚本获取不到video
> 
> 那估计就是第二个commit导致的了

![屏幕截图 2024-06-06 214511](https://github.com/Izumiko/jellyfin-danmaku/assets/80084984/7d0e3148-75c4-4bdb-9355-feb638849137)
我回退了这个[commit](https://github.com/9channel/dd-danmaku/commit/d79a8ac792f5008f7225fa45f96b208c16145d2d)就正常了

**Comment by Izumiko** [comment]
@Xarth-Mai 看来 #48 还得再斟酌一下

**Comment by Izumiko** [comment]
@Hammer2333 你直接在控制台执行`document.getElementById('reactRoot')`的话，能获得元素么

**Comment by Hammer2333** [comment]
> document.getElementById('reactRoot')

不能，直接返回了null
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/80084984/5d5277f2-6dc2-4023-9401-937e0ec26e0f)

**Comment by Izumiko** [comment]
> > document.getElementById('reactRoot')
> 
> 不能，直接返回了null ![image](https://private-user-images.githubusercontent.com/80084984/337294117-5d5277f2-6dc2-4023-9401-937e0ec26e0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODIzNjQsIm5iZiI6MTcxNzY4MjA2NCwicGF0aCI6Ii84MDA4NDk4NC8zMzcyOTQxMTctNWQ1Mjc3ZjItNmRjMi00MDIzLTk0MDEtOTM3ZTBlYzI2ZTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEzNTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MjQ4NTE0YjA1MTA0OGM5M2U2MWZhYjhhMzQyYTRhMjdjMWFlZWMzMzJkMzI4NjY1Y2Y5NzkyZjAzZjQ0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pka-YvV9-zJCnOAD4BUOqv8HKUThe8ocRk6WBQNyZzo)

咦，你的jellyfin是原版么，有没有经过修改？版本号是多少。我们的里面是有这个div的
![图片](https://github.com/Izumiko/jellyfin-danmaku/assets/5195868/2a5a7fee-2a73-44c7-8897-24e3c1874165)

**Comment by Hammer2333** [comment]
> > > document.getElementById('reactRoot')
> > 
> > 
> > 不能，直接返回了null ![image](https://private-user-images.githubusercontent.com/80084984/337294117-5d5277f2-6dc2-4023-9401-937e0ec26e0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODIzNjQsIm5iZiI6MTcxNzY4MjA2NCwicGF0aCI6Ii84MDA4NDk4NC8zMzcyOTQxMTctNWQ1Mjc3ZjItNmRjMi00MDIzLTk0MDEtOTM3ZTBlYzI2ZTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEzNTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MjQ4NTE0YjA1MTA0OGM5M2U2MWZhYjhhMzQyYTRhMjdjMWFlZWMzMzJkMzI4NjY1Y2Y5NzkyZjAzZjQ0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pka-YvV9-zJCnOAD4BUOqv8HKUThe8ocRk6WBQNyZzo)
> 
> 咦，你的jellyfin是原版么，有没有经过修改？版本号是多少。我们的里面是有这个div的 ![图片](https://private-user-images.githubusercontent.com/5195868/337295059-2a5a7fee-2a73-44c7-8897-24e3c1874165.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODI1MTcsIm5iZiI6MTcxNzY4MjIxNywicGF0aCI6Ii81MTk1ODY4LzMzNzI5NTA1OS0yYTVhN2ZlZS0yYTczLTQ0YzctODg5Ny0yNGUzYzE4NzQxNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTM1NjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdhMDkxMzdkOWM3MTEyNDQ2NjhjZjUwNjUyYjU5MDllYWY3ODA5MGRjYWM0YmQ5OTFlYzIwNGI3MTkyYWM3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fAFipZTTDwdUcJV30QPn7-5bTVrHIEof3scJjgolQNM)

在官方下载的serverclient，版本是10.8.11，对于页面的修改应该只有自定义css了吧，我禁用一下再试试

**Comment by Hammer2333** [comment]
@Izumiko 
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/80084984/ff7b9808-b0ec-4301-b4ce-f4ad3fd9b7af)
就很奇怪，没找到这个元素，难不成winServer和linuxServer还有这些奇怪的区别

**Comment by Izumiko** [comment]
@Hammer2333 找到原因了， @Xarth-Mai 的PR使用的reactRoot是在10.9.x里面添加，旧版里面没有这个元素

图里上边是10.9的index.html，下边是10.8的
![图片](https://github.com/Izumiko/jellyfin-danmaku/assets/5195868/dcaa4a03-e081-4260-bc5c-66a3ade26256)

**Comment by Hammer2333** [comment]
> @Hammer2333 找到原因了， @Xarth-Mai 的PR使用的reactRoot是在10.9.x里面添加，旧版里面没有这个元素
> 
> 图里上边是10.9的index.html，下边是10.8的 ![图片](https://private-user-images.githubusercontent.com/5195868/337300647-dcaa4a03-e081-4260-bc5c-66a3ade26256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODM0ODcsIm5iZiI6MTcxNzY4MzE4NywicGF0aCI6Ii81MTk1ODY4LzMzNzMwMDY0Ny1kY2FhNGEwMy1lMDgxLTQyNjAtYmM1Yy02NmEzYWRlMjYyNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTQxMzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDkyZDdkNGExOGVlMjBhZmU5YmFmOTU1ZTg4ZThmNDQwYjI1OGJlNGNkMzBmMTUxOGI0YmM1NGVlYTk0NjYwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y10_bmRSFrclD-LK6UYxuGkNaPiFsyfMI-DjxE-FbRg)

懂了，我落后版本了，这就去更新（）

**Comment by Izumiko** [comment]
我把新旧写法结合了一下，现在10.8应该也能用了

**Comment by Izumiko** [comment]
> > @Hammer2333 找到原因了， @Xarth-Mai 的PR使用的reactRoot是在10.9.x里面添加，旧版里面没有这个元素
> > 图里上边是10.9的index.html，下边是10.8的 ![图片](https://private-user-images.githubusercontent.com/5195868/337300647-dcaa4a03-e081-4260-bc5c-66a3ade26256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODM0ODcsIm5iZiI6MTcxNzY4MzE4NywicGF0aCI6Ii81MTk1ODY4LzMzNzMwMDY0Ny1kY2FhNGEwMy1lMDgxLTQyNjAtYmM1Yy02NmEzYWRlMjYyNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTQxMzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDkyZDdkNGExOGVlMjBhZmU5YmFmOTU1ZTg4ZThmNDQwYjI1OGJlNGNkMzBmMTUxOGI0YmM1NGVlYTk0NjYwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y10_bmRSFrclD-LK6UYxuGkNaPiFsyfMI-DjxE-FbRg)
> 
> 懂了，我落后版本了，这就去更新（）

10.9的元数据刷新还有bug，不知道修好了没有，我还在等😂

**Comment by Xarth-Mai** [comment]
> @Hammer2333 找到原因了， @Xarth-Mai 的PR使用的reactRoot是在10.9.x里面添加，旧版里面没有这个元素

!!我用的10.10.0 没注意这个问题/(ㄒoㄒ)/~~

**Comment by Izumiko** [comment]
> > @Hammer2333 找到原因了， @Xarth-Mai 的PR使用的reactRoot是在10.9.x里面添加，旧版里面没有这个元素
> 
> !!我用的10.10.0 没注意这个问题/(ㄒoㄒ)/~~

好家伙，直接上unstable啊

**Comment by Xarth-Mai** [comment]
> 好家伙，直接上unstable啊

好像没遇到什么bug，lucky
