### ISSUE TITLE
[BUG]无法获取用户的session信息

### ISSUE THREAD

**Issue by Geeksun2018** [Izumiko/jellyfin-danmaku#5]
jellyfin 版本是docker，10.8.12，jellyfin-danmaku版本是最新版。
不太确定是不是因为没获取到session的信息导致无法查询到视频对应的弹幕。
![8468f076d6344c902b5d6523605dda7](https://github.com/Izumiko/jellyfin-danmaku/assets/42086593/f4d247d5-69d4-4286-b4c1-b21a3a3bb927)
![322bc3af29cde1d04a57724c3c6843b](https://github.com/Izumiko/jellyfin-danmaku/assets/42086593/f42684b7-322c-45b8-a310-50ee16925fd4)

**Comment by cliffxzx** [comment]
+1, 在給 query string 時打 api 時返回空陣列，不帶 query 的 string 時，返回的物件有要查詢的 devid 及 userid。

**Comment by Geeksun2018** [comment]
> +1, 在給 query string 時打 api 時返回空陣列，不帶 query 的 string 時，返回的物件有要查詢的 devid 及 userid。

我在新版本中修复了这个问题，正在不同客户端测试新版本，预计过两天就会发布，到时候可以再试试！

**Comment by cliffxzx** [comment]
剛剛才看到您的 PR，感謝大大修復！期待發布😋

**Comment by Geeksun2018** [comment]
> +1, 在給 query string 時打 api 時返回空陣列，不帶 query 的 string 時，返回的物件有要查詢的 devid 及 userid。

我找到原因了！你是不是也配置了nginx，可以修改一下nginx的配置文件，估计某些请求头没有带上。
可以参考这个：https://tech.joyzhanglife.com/index.php/archives/71/

**Comment by cliffxzx** [comment]
沒錯 一模一樣 orz，改完 proxy_header 後解決了。謝謝！

**Comment by Geeksun2018** [comment]
> 沒錯 一模一樣 orz，改完 proxy_header 後解決了。謝謝！

你也用的这个面板嘛hhh？Nginx Proxy Manager

**Comment by cliffxzx** [comment]
<img width="497" alt="image" src="https://github.com/Izumiko/jellyfin-danmaku/assets/44764053/8843fb67-3921-446d-b04c-b53998f2ef3f">


對啊 哈哈，懶得搞 traefik。 在 Nginx Proxy Manager 加上後面 3 行就解決了
