### ISSUE TITLE
[BUG]未知的弹幕重复加载问题

### ISSUE THREAD

**Issue by Youwenqwq** [Izumiko/jellyfin-danmaku#50]
**Version**

- Jellyfin版本：10.8.13
- ede.js版本：621ac57

**Describe the bug**
如图，加载番剧弹幕时部分弹幕会重复显示2次。单独过滤其他源，仅保留b站源如图，仍有大量重复且同时的弹幕。弹弹play同样加载b站源则不会。

测试关闭简繁转换依然存在问题。

演示番剧为魔法少女小圆S01E01，实测CLANNAD之类的也会出现。鉴于没有人报告，怀疑是不是我本地出现问题，但由于不知道如何检查，故发此issue。

![image](https://github.com/Izumiko/jellyfin-danmaku/assets/25259258/874eab3f-10f9-4d4a-9afe-7962a1791730)

**Comment by Izumiko** [comment]
b站同一个番剧有两个播放地址，弹弹play也收录了两遍。之前改成额外获取第三方弹幕时，是把所有的弹幕地址都下载了一遍，所以b站的弹幕有两份。然后采用剔除相同弹幕id的方式删除掉重复弹幕。

根据你的问题，我发现两个播放地址下载的弹幕中，相同的弹幕大多有相同的cid，但还有一部分的是不一样的。。。

左：http://bangumi.bilibili.com/anime/2539/play#63470
右：http://www.bilibili.com/video/av1358885/index_1.html

![图片](https://github.com/Izumiko/jellyfin-danmaku/assets/5195868/2ef382c7-d3f0-444f-8110-e648bcb870fb)

**Comment by Izumiko** [comment]
修改了一下重复的判定条件，你试试最新提交的版本

**Comment by Youwenqwq** [comment]
> 修改了一下重复的判定条件，你试试最新提交的版本

![image](https://github.com/Izumiko/jellyfin-danmaku/assets/25259258/807e94f8-085c-4746-b177-5bd3dd4c94c7)

经测试已经不会出现重复，感谢修复！
