### ISSUE TITLE
[UR/FR]弹幕时移支持

### ISSUE THREAD

**Issue by Youwenqwq** [Izumiko/jellyfin-danmaku#51]
由于部分动漫，本地下载的蓝光片源和弹幕网的WEB片源存在部分差异（例如web开头有ANIPLEX但部分蓝光片源没有），故希望可以调整弹幕，增加时移，自主设置偏移量±x.x秒，以便同步弹幕，获得更好体验。

**Comment by Izumiko** [comment]
已实现，在设置界面可以设置当前集的弹幕偏移时间，单位是秒
