### ISSUE TITLE
[BUG]jellyfin10.9.6似乎用不了nginx反向代理的模式了

### ISSUE THREAD

**Issue by index20481** [Izumiko/jellyfin-danmaku#52]
**Version**
jellyfin verson
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/77374137/9a509856-78d1-4c41-8966-8985bc62bb31)

**Describe the bug**
之前在用jellyfin10.8.13的时候是可以使用的，nginx的配置应该是没问题的，最近更新到10.9.6了之后发现似乎用不了了，但是如果用tampermonkey插件的话还是可以用的.
**使用tampermonkey插件**
![image](https://github.com/Izumiko/jellyfin-danmaku/assets/77374137/3dc8bcf5-bb11-463f-9b18-7fd9065b3263)

**使用nginx**

![image](https://github.com/Izumiko/jellyfin-danmaku/assets/77374137/5538b72f-7351-4381-92da-3e19d60bbd03)

![image](https://github.com/Izumiko/jellyfin-danmaku/assets/77374137/147241f6-29d9-42cf-ac4c-fa74bc918120)

**Comment by Izumiko** [comment]
我用Caddy倒是没啥问题，你nginx的配置文件是怎么写的？

**Comment by index20481** [comment]
我直接用的那个完整示例

`

worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;


    location / {
        proxy_pass http://192.168.3.5:8096;
        proxy_pass_request_headers on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        # 在流式传输时禁用缓冲
        proxy_buffering off;
    }

    location = /web/index.html {
        proxy_pass http://192.168.3.5:8096/web/index.html;
        proxy_pass_request_headers on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        # 禁用与后端压缩并侧载脚本
        proxy_set_header Accept-Encoding "";
        sub_filter '</body>' '<script src="https://jellyfin-danmaku.pages.dev/ede.user.js" defer></script></body>';
        sub_filter_once on;
    }
    
        location /socket {
        proxy_pass http://192.168.3.5:8096;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }


    }


}
`

之前是可以用的，应该没啥问题

**Comment by Izumiko** [comment]
这里
```
location = /web/index.html {
```

Jellyfin 10.9 的URL后边不带`index.html`了，你可以在地址栏那确认一下，所以得删去

**Comment by index20481** [comment]
这个我后来也试过了，还是不行

**Comment by Izumiko** [comment]
刚才忘记说下一行的proxy_pass里面的也得删了。你看一下最新的那个完整示例，他用的是10.10版的Jellyfin，也能正确替换

**Comment by Izumiko** [comment]
另外，更改之后，还要取消注册service worker，不然浏览器还会使用自己缓存的旧版网页

**Comment by index20481** [comment]
okok解决了

**Comment by index20481** [comment]
> 另外，更改之后，还要取消注册service worker，不然浏览器还会使用自己缓存的旧版网页

绷不住了，万万没想到是我没清缓存导致的(シ_ _)シ

**Comment by Xarth-Mai** [comment]
https://github.com/Izumiko/jellyfin-danmaku/issues/8
之前更新了一下 新版本url路径变了 但是添加为桌面app时的url路径没变 所以我加了个301重定向
