### ISSUE TITLE
[UR/FR] 建议将Cloudflare workers反代改为DNS反代

### ISSUE THREAD

**Issue by repo-ooo** [Izumiko/jellyfin-danmaku#54]
理由：

CF workers免费用户每天有10w次访问上限，超限无法提供服务

DNS反代无限次数

方法：

Cloudflare Dashborad中添加DNS记录

CNAME  api -> api.dandanplay.net 打开小黄云代理

Rules -> Transform Rules -> Modify Response Header

用 `hostname` 匹配 `api.mydomain.com`

修改 `Access-Control-Allow-Origin = *`

之后任何`api.mydomain.com`的访问都等价于`api.dandanplay.net`的访问，不需要URL rewrite `/cors`

**Comment by Izumiko** [comment]
感谢建议，目前请求数量在1k量级，距离上限还远，后面访问量高了的话就换用你这个方案

**Comment by Izumiko** [comment]
测试了一下，貌似不太行。添加了如下规则：
![图片](https://github.com/user-attachments/assets/05fc5452-d085-45e9-9f68-2335b1cc0188)
![图片](https://github.com/user-attachments/assets/af3eeea6-cd0c-40c4-b605-e627e163bba1)

然后测试时OPTIONS请求就报404了。应该是用你这个模式在弹弹play服务器上Host不匹配吧

**Comment by repo-ooo** [comment]
怪我太想当然，没有真正测试，试了一下确实用CNAME反代会把Options请求也给反代到`api.dandanplay.net`，但源站又不支持Options然后报错。

现在看来确实没有什么比现有方案更好的办法
