### ISSUE TITLE
[UR/FR]请问能否增加读取本地弹幕文件的功能，以便更好的配合其他弹幕刮削软件使用

### ISSUE THREAD

**Issue by UltraRiderRanger** [Izumiko/jellyfin-danmaku#55]
非常好弹幕插件，使我jelly滨洲旋转。
能否自动读取本地弹幕文件？
使用弹幕刮削插件下载的弹幕会以xml保存在本地，刮削插件的匹配能力相对较强，api数量多，能比较好的匹配很多电影电视剧的弹幕。
而且这样的话离线也可以用了捏

**Comment by Izumiko** [comment]
我后面找个时间加一下。这个功能得配合jellyfin-plugin-danmu插件的API实现，不能直接读取xml文件

**Comment by Izumiko** [comment]
增加了一下xml的加载功能，需要在设置里面启用一下。目前我jellyfin-plugin-danmu插件只启用了弹弹play的源，生成的xml可以成功显示
