### ISSUE TITLE
[BUG]本地XML弹幕无法使用

### ISSUE THREAD

**Issue by Levin-7** [Izumiko/jellyfin-danmaku#58]
**Version**
Jellyfin: 10.8.11
Jellyfin-Danmu: 1.7.11.0

**Describe the bug**
无法调用本地XML弹幕

**Screenshots**
![image](https://github.com/user-attachments/assets/b61ef480-ff0f-4786-bb5f-9b6dcc097a83)

**Additional context**
附疑似报错log
[log.txt](https://github.com/user-attachments/files/17088307/log.txt)

**Comment by Izumiko** [comment]
写这个代码的时候只测试了新版，忘记Jellyfin旧版(<10.9)的路径里面还有index.html了。
你访问下面这个地址应该能看到弹幕内容吧？
http://192.168.50.249:8096/api/danmu/9f8e4d370c51f16aba33951d3325e64d/raw

**Comment by Levin-7** [comment]
可以

**Comment by Izumiko** [comment]
修了，你再试试

**Comment by Levin-7** [comment]
OK啦，谢谢大大了
