### ISSUE TITLE
[BUG]无法显示本地XML弹幕在Jellyfin10.10.0

### ISSUE THREAD

**Issue by GoFightNow** [Izumiko/jellyfin-danmaku#63]
**Version**

- [nyanmisaka/jellyfin](https://hub.docker.com/r/nyanmisaka/jellyfin) 10.10.0
- Jellyfin danmaku extension 1.49
- [jellyfin-plugin-danmu](https://github.com/cxfksword/jellyfin-plugin-danmu) v2.0.9.0

**Describe the bug**

我在使用danmaku油猴插件打开本地XML时，总是无法获取本地XML

**To Reproduce**

在Jellyfin某个电影中，使用字幕搜索，下载bilibili对应电影的字幕到本地（格式XML，可以在弹弹PLAY正常使用）。但插件无法获取，显示本地弹幕加载失败

**Expected behavior**

希望能正常使用该功能，在web的体验能更进一步

**Screenshots**

![image](https://github.com/user-attachments/assets/b64c124e-2daf-4dfd-9544-740947292eb8)

**Additional context**

我查看了[#58](https://github.com/Izumiko/jellyfin-danmaku/issues/58)，但我并未找到类似的log，您能告诉我该如何提供log吗，检索什么关键词

**Comment by GoFightNow** [comment]
我在控制台进行debug。在请求api/danmu/someid/raw后，返回的response没有ok属性也没有text属性，在接下来判断if (!response.ok)的时候会直接为true，然后返回null。其他人使用[nyanmisaka/jellyfin10.10.0 dev (latest: 24/10/27)](https://hub.docker.com/r/nyanmisaka/jellyfin)是否有遇到该问题呢？
这个是我自有的bug吗，我看到最新的issues好像没有遇到这种问题

**Comment by Izumiko** [comment]
我用官方的docker镜像`jellyfin/jellyfin:latest`，插件版本和你一样，没有遇到这个问题

**Comment by GoFightNow** [comment]
> 我用官方的docker镜像`jellyfin/jellyfin:latest`，插件版本和你一样，没有遇到这个问题

大佬您好上次提供的信息不全，我是使用油猴脚本的方式实现的，chrome版本是`版本 130.0.6723.92（正式版本） （64 位）`，经过早上几次调试。我大概发现问题所在，不过我真不太懂js代码，希望对您有帮助。

我发现makeGetRequest函数因为isInTampermonkey可能返回不同的格式，为true则返回的是response.responseText是文本，为false则返回的是Response对象。我isInTampermonkey是true，一直返回了xml文本，导致无法判断ok属性和提取text。
如果我将getCommentsByPluginApi里面部分代码修改，我可以正常加载本地弹幕。
这是源代码
```js
    async function getCommentsByPluginApi(jellyfinItemId) {
        const path = window.location.pathname.replace(/\/web\/(index\.html)?/, '/api/danmu/');
        const url = window.location.origin + path + jellyfinItemId + '/raw';
        const response = await makeGetRequest(url);
        if (!response.ok) {
            return null;
        }
        const xmlText = await response.text();
        if (!xmlText || xmlText.length === 0) {
            return null;
        }
```
修改后（我知道很粗糙）
```js
    async function getCommentsByPluginApi(jellyfinItemId) {
        const path = window.location.pathname.replace(/\/web\/(index\.html)?/, '/api/danmu/');
        const url = window.location.origin + path + jellyfinItemId + '/raw';
        const response = await makeGetRequest(url);
        const xmlText = await response;
        if (!xmlText || xmlText.length === 0) {
            return null;
        }
```

我感觉应该将makeGetRequest修改成返回同样的东西才对，但是我直接修改makeGetRequest函数返回response后，造成了获取在线字幕的不可用（摊手┑(￣Д ￣)┍）

**Comment by Izumiko** [comment]
之前写的时候直接用了自定义的makeGetRequest，实际请求同一个服务器没跨域的问题，这里用fetch就行。改了一版，你更新试试

**Comment by GoFightNow** [comment]
ok可用，谢谢大佬，我将关闭这个问题
