### ISSUE TITLE
[BUG]10.10.0 jellyfin ，特定条件下弹幕插件不能成功加载

### ISSUE THREAD

**Issue by Yukari-Lily** [Izumiko/jellyfin-danmaku#64]
Jellyfin版本：10.10.0

安装方式：4.windows 服务端，修改index.html

现象：升到10.10.0后发现用户权限会导致弹幕插件不能成功加载，只有勾选[允许此用户管理服务器]后，这个用户才能正常加载弹幕插件

![IMG_20241030_020840](https://github.com/user-attachments/assets/9c5b403e-22a8-4786-bbad-691338865aca)
![IMG_20241030_020852](https://github.com/user-attachments/assets/66b1423d-1bf3-424b-8ac1-bf661494f1f2)

**Comment by lonzzi** [comment]
#62 可以先试试我目前改的版本：https://jellyfin-danmaku-b32.pages.dev/ede.user.js

**Comment by Yukari-Lily** [comment]
> #62 可以先试试我目前改的版本：https://jellyfin-danmaku-b32.pages.dev/ede.user.js

可以的，感谢！
