### ISSUE TITLE
[BUG]最近一次更新过后，页面按钮不能正常显示，控制台也报错获取不到itemid

### ISSUE THREAD

**Issue by Hammer2333** [Izumiko/jellyfin-danmaku#65]
Version

[[jellyfin-server-windows](https://github.com/jellyfin/jellyfin-server-windows)]10.9.11
Describe the bug

今天打开视频后发现有报错，上次看番还是正常的

![1](https://github.com/user-attachments/assets/b4dc9847-ef99-48a4-904f-60c072c309ab)

**Comment by Izumiko** [comment]
代码更新后只测试了10.10+版本的兼容性，旧版没测试，现在添加了一个版本的检查，你再试试

**Comment by Hammer2333** [comment]
> 代码更新后只测试了10.10+版本的兼容性，旧版没测试，现在添加了一个版本的检查，你再试试

已经正常了，非常感谢
