### ISSUE TITLE
[BUG]10.10.0版本安卓无法加载

### ISSUE THREAD

**Issue by APecme** [Izumiko/jellyfin-danmaku#67]
![Screenshot_20241107_153635_Jellyfin](https://github.com/user-attachments/assets/5085ec9f-dd7a-4207-a5ff-0b5b349434fe)
更新了10.10.0版本之后安卓端使用网页播放器好像就不能加载出来了，使用游览器就没有问题。

**Comment by Izumiko** [comment]
又测试了一下，不是下面的原因，开了翻墙就能正常加载，估计是Cloudflare的pages服务被GFW干扰了
---

~测试了一下，这种环境下安卓客户端好像没请求index.html文件，所以原来方法里面说的加载js脚本的方式都失效了。~

我自己用Caddy，测试了一下把脚本附加到main.jellyfin.bundle.js这个脚本后面，能够播放了。

方法2.2的`filter`部分更新为下面的设置：
```Caddyfile
    filter {
        path .*/web/main\.jellyfin\.bundle\.js.*
        search_pattern $
        replacement `;(function(){
            var script = document.createElement('script');
            script.src = 'https://jellyfin-danmaku.pages.dev/ede.user.js';
            script.defer = true;
            document.body.appendChild(script);
        })();`
        content_type text/javascript
    }
```
![Screenshot_20241107-180322_Jellyfin](https://github.com/user-attachments/assets/9c541f9d-1363-4eba-a8d3-3539b328c84f)

**Comment by Izumiko** [comment]
啊，才注意到你的按钮位置和我的不一样，我在手机和Pad上都没见过这个布局，你的有点像emby的？估计你用现在这个版本还是会有问题。现在的版本我是让弹幕按钮追加到了暂停按钮父元素的后面

**Comment by APecme** [comment]
是jellyfin呢，昨天更新到jellyfin特供10.10.0然后客户端就变成这样了，好像也不是被墙的原因，因为现在可以正常使用了，手机客户端的版本是2.6.2只有在客户端上有出现问题

**Comment by mayziran** [comment]
> 是jellyfin呢，昨天更新到jellyfin特供10.10.0然后客户端就变成这样了，好像也不是被墙的原因，因为现在可以正常使用了，手机客户端的版本是2.6.2只有在客户端上有出现问题

我的2.6.3也和你一样，只在安卓端这样，ipad的网页 都没问题@Izumiko

**Comment by Izumiko** [comment]
@mayziran 你有没有按照我后来在readme中新改的脚本地址更新一下服务端设置？

我这里2.6.3加载是正常的
![Screenshot_2025-07-23-09-49-19-76_4b95a63cd60fd3e0f30739d89812bf6c.jpg](https://github.com/user-attachments/assets/1a58f5bc-e7d0-4fea-b5d5-82565667052b)

**Comment by mayziran** [comment]
> [@mayziran](https://github.com/mayziran) 你有没有按照我后来在readme中新改的脚本地址更新一下服务端设置？
> 
> 我这里2.6.3加载是正常的 ![Screenshot_2025-07-23-09-49-19-76_4b95a63cd60fd3e0f30739d89812bf6c.jpg](https://github.com/user-attachments/assets/1a58f5bc-e7d0-4fea-b5d5-82565667052b)

我是刚刚才安装的，docker compose 加的 entrypoint: sh -c "sed -i 's#</div></body>#</div><script src=\"https://cdn.jsdelivr.net/gh/Izumiko/jellyfin-danmaku@gh-pages/ede.user.js\" defer></script></body>#' /jellyfin/jellyfin-web/index.html && exec /jellyfin/jellyfin" ，play商店下载的最新jellyfin，我的播放器界面和你的好像不同是和他的一样的界面

**Comment by Izumiko** [comment]
@mayziran 奇怪了，我尝试切换到普通用户，还有尝试重装了客户端，都没法复现你们的界面

![Screenshot_2025-07-23-10-09-27-33_4b95a63cd60fd3e0f30739d89812bf6c.jpg](https://github.com/user-attachments/assets/58697433-defe-498d-b768-054a9eb7a47c)

**Comment by mayziran** [comment]
> [@mayziran](https://github.com/mayziran) 奇怪了，我尝试切换到普通用户，还有尝试重装了客户端，都没法复现你们的界面
> 
> ![Screenshot_2025-07-23-10-09-27-33_4b95a63cd60fd3e0f30739d89812bf6c.jpg](https://github.com/user-attachments/assets/58697433-defe-498d-b768-054a9eb7a47c)

我重装app以后好了，我猜应该是因为之前没修改服务端之前就登陆了的原因
