### ISSUE TITLE
[BUG]@match失效

### ISSUE THREAD

**Issue by Geeksun2018** [Izumiko/jellyfin-danmaku#7]
为什么不能@match无法匹配到jellyfin的主页呀？@match        *://*/*/web/index.html，这个应该是能匹配到的，好奇怪。
我尝试在docker上直接修改html文件，发现并不是总能生效，只能强制指定当前jellyfin的主页。

**Comment by Xarth-Mai** [comment]
在https://github.com/Izumiko/jellyfin-danmaku/pull/10中修复
